server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html; # Essentiel pour le routage des SPA
    }

    # Optionnel : Contrôle du cache pour les assets statiques (JS, CSS, images)
    # Améliore la performance en production
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg|eot)$ {
        expires 1y;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
